Additional min proto format testing
npazosmendez/prometheus pull request #3
Opened 2023-11-13 19:16 UTC by cstyan

refactor new version flag to make it easier to pick a specific format instead of having multiple flags, plus add new formats for testing

I've added lots of TODO comments that we should audit at some point before we merge into upstream main

2023-11-14 19:06 UTC, npazosmendez approved these changes
looks good, the flag refactor will be useful as we make progress.

I'm wondering if we should discard  `min-64-fixed` now, based on [your experiments](https://github.com/prometheus/prometheus/issues/13105#issuecomment-1806593500)

2023-11-14 19:06 UTC, npazosmendez commented on cmd/prometheus/main.go
> +	// todo: how to use the enable feature flag properly + use the remote format enum type
I suppose that once our work is ready to be merged to `main`, we'll have converged to a single format that can be behind a single feature flag, so this won't be a problem.

(non-actionable comment)

2023-11-14 19:06 UTC, npazosmendez commented on web/ui/package-lock.json
This looks unrelated

2023-11-14 19:20 UTC, npazosmendez commented on storage/remote/queue_manager.go
> +	MinBytes // two 32bit fixed, similar to optimized but not varints + no manual marshalling optimization
This is actually two varints


```suggestion
	MinBytes // two varints, similar to optimized but no manual proto marshaling optimization. varints are encoded when building the struct 
```

2023-11-14 19:29 UTC, npazosmendez requested changes

2023-11-14 19:29 UTC, npazosmendez commented on storage/remote/queue_manager.go
> +				s.sendMin32Samples(ctx, pendingMin32Data[:n], symbolTable.LabelsString(), nPendingSamples, nPendingExemplars, nPendingHistograms, pBuf, &buf)
This should be `sendMinBytes`

2023-11-15 18:25 UTC, cstyan commented
Results for the latest commit
![2023-11-14-195602_2517x1088_scrot](https://github.com/npazosmendez/prometheus/assets/3246492/1ef016fb-9895-4785-80b5-385420b3f8c7)
![2023-11-14-195611_2515x915_scrot](https://github.com/npazosmendez/prometheus/assets/3246492/c7eb80ae-c87f-4e2f-a818-1eefe0565418)
![2023-11-14-195619_2518x1030_scrot](https://github.com/npazosmendez/prometheus/assets/3246492/0ba4dce4-93c4-4b1c-aedc-45a65f18a25a)

2023-11-16 19:36 UTC, npazosmendez approved these changes
To double check I ran the benchmarks locally and, at least from a short ~20min run, I'm getting similar results.


______________________

Here's my take:
- `v11-min32-fixed`: discard. 2nd worst in network by a considerable margin, with no other gains to balance (e.g. sender/receiver CPU).
- `v11-min64-fixed`: discard. Worst in network usage, 2nd worst in sender's CPU. And while the receiver's CPU looks good, it's the stat I would trust the less from our benchmarks (as in, I don't think it is representative enough for Mimir, Thanos, etc.). And even if it was, other formats have similar or better receiver CPU. 
- `v11-min-bytes`: discard. This is basically the same as `v11-min32-optimized-varint` but with a less intuitive message definition. As I mentioned [here](https://github.com/prometheus/prometheus/issues/13105#issuecomment-1808094501), I'd rather have a custom marshaller for performance than a weird proto definition. I'm pretty sure that the CPU difference in the sender is because of [this line](https://github.com/prometheus/prometheus/blob/eec966377d6774ac6b9f4c17ad65c06bf0b7b802/prompb/custom.go#L161) in the `v11-min32-optimized-varint`  version, which may be optimizable; in any case, it's no big difference IMO.
- `v11-min-len-bytes`: discard. Similar reasoning as above, but comparing it to `v11-min-len`. The sender's CPU difference is not significant and probably not a representative measurement. Even worse, for this case there seems to be a considerable difference in receiver's CPU. Although as I said I don't think that's our more reliable metric.
- `v11-min32-optimized-varint`: probably discard. Stats are a bit worse than `v11-min-len`, but not by much. The only upside I see is the decoding is slightly easier to implement: `string[int1: int1+int2]`. 
- `v11-min-len`: keep. The only downside I see is decoding is harder and the message is less intuitive; but still this is my vote. Side note: we can even try changing the encoded symbol strings `[]byte` to a `[]string` for a nicer message; the underlying bytes should be the same (I think), and the unmarshaling can be optimized to get results similar to the current ones.

2023-11-21 12:48 UTC, npazosmendez approved these changes

2023-11-21 12:48 UTC, npazosmendez commented on storage/remote/queue_manager.go
>  			if len(batch) > 0 {
Looks like the `case MinLen:` is missing here.

2023-11-21 12:48 UTC, npazosmendez commented on web/ui/package-lock.json
This reappeared :grin:

2023-11-21 13:15 UTC, npazosmendez commented on web/web.go
> +	fmt.Println("rw format for handler is: ", o.RemoteWriteFormat)
Do we want to keep this or was it left from debugging?

2023-11-21 16:43 UTC, npazosmendez commented on scripts/remotewrite11-bench/run.sh
> +INSTANCES+=('sender-v11-min-len;--remote-write-format 5;receiver-v11-min-len;--remote-write-format 5')
This should be 2 now
```suggestion
INSTANCES+=('sender-v11-min-len;--remote-write-format 2;receiver-v11-min-len;--remote-write-format 2')
```

2023-11-23 22:25 UTC, cstyan commented
The current `tests` failure is just 
```
example_write_adapter/server.go:1: : # github.com/prometheus/prometheus/documentation/examples/remote_storage/example_write_adapter
example_write_adapter/server.go:61:22: undefined: remote.DecodeMinimizedWriteRequest (typecheck)
```
which we can't fix until everything is merged into an upstream branch, and then we update `go.mod` in `documentation/examples/remote_storage` to be a new prom version.

2023-11-23 22:30 UTC, npazosmendez commented
Nice work. I say we merge and figure out the remaining ones later, in the Prometheus' PR

2023-11-23 22:34 UTC, merged